### ISSUE TITLE
Issue when trying to switch

### ISSUE THREAD

**Issue by djdarlo** [eelmafia/octopus-minmax#47]
This is the first time the code has tried to switch but I got the below..... any ideas?  I plan to upgrade to v0.3.0 today so maybe that will fix it?

Octobot on. Starting comparison of today's costs...
Total potential cost on AGILE: £1.01 vs your current cost on GO: £1.30
Initiating Switch to AGILE
Traceback (most recent call last):
  File "/app/main.py", line 324, in run_tariff_compare
    compare_and_switch()
  File "/app/main.py", line 305, in compare_and_switch
    switch_tariff(opposite_tariff[curr_tariff])
  File "/app/main.py", line 239, in switch_tariff
    page.get_by_placeholder("Email address").click()
  File "/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py", line 15450, in click
    self._sync(
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
  - waiting for get_by_placeholder("Email address")
  -     - locator resolved to <input required="" type="email" name="username" maxlength="512" id="id_username" placeholder="Email address"/>
  -   - attempting click action
  -     2 × waiting for element to be visible, enabled and stable
  -       - element is visible, enabled and stable
  -       - scrolling into view if needed
  -       - done scrolling
  -       - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -     - retrying click action
  -     - waiting 20ms
  -     2 × waiting for element to be visible, enabled and stable
  -       - element is visible, enabled and stable
  -       - scrolling into view if needed
  -       - done scrolling
  -       - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -     - retrying click action
  -       - waiting 100ms
  -     55 × waiting for element to be visible, enabled and stable
  -        - element is visible, enabled and stable
  -        - scrolling into view if needed
  -        - done scrolling
  -        - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -      - retrying click action
  -        - waiting 500ms

**Comment by joeShuff** [comment]
I've seen this tonight too. Ran it on my local machine through python and it worked fine. Gonna add some more logs and screenshots to my docker build and run an image to output images if that will make a difference.

Will keep updated.

**Comment by adyoull** [comment]
> I've seen this tonight too. Ran it on my local machine through python and it worked fine. Gonna add some more logs and screenshots to my docker build and run an image to output images throughout the playwright journey so when it goes wrong, we can see the site.
> 
> Will keep this updated.

is it possible for you to add an optional debug flag into the general image, so that I can try and see what's happening with my issue relating to multiple accounts linked to an email, as I'm not au fait with playwright and trying to use:

`        page.screenshot({ path: 'screenshot.png', fullPage: true });
`

Doesn't seem to work as I expected it to produce a screenshot in the app folder within the docker image.

**Comment by joeShuff** [comment]
whats the problem you're having exactly? you have multiple accounts that use the same email?

The code you've provided isn't quite python syntax. To screenshot the state of the page at a given point its
`page.screenshot(path = "filename.png")`

**Comment by eelmafia** [comment]
My switch tonight was successful and I've never encountered this before. If you're able to run it on your computer you can change `headless` to `False` and it will open a browser UI so you can see what's going on in real time. 

```py
browser = playwright.firefox.launch(
            headless=False) # From True to False
```

**Comment by joeShuff** [comment]
you run through docker?

Mine didn't switch last night, cosy has been cheapest for me for several days now.

**Comment by eelmafia** [comment]
> you run through docker?
> 
> Mine didn't switch last night, cosy has been cheapest for me for several days now.

No I ran it outside of docker on my machine so I can watch the browser in case this happens to me as well. If it's only happening in docker it's very puzzling.

**Comment by eelmafia** [comment]
I think there's a problem with our ARM build. 

I had https://github.com/eelmafia/octopus-minmax/pull/39 running on my RPI tonight and it tried to switch but failed.

I then ran a `ONE_OFF` inside a docker container on my windows machine and it switched me successfully.

**Comment by joeShuff** [comment]
if you built the latest version of the build I pushed last night, then it takes screenshots and puts them in the /config folder. If you can access that folder then you'll be able to see the screenshot outputs.

**Comment by joeShuff** [comment]
Also I saw the error on my docker and my server is amd64 arch so I dont think its just ARM.

Will see if I can do some investigation tomorrow as switching to the tariff you're already on seems to work the same and not break anything.

**Comment by eelmafia** [comment]
> if you built the latest version of the build I pushed last night, then it takes screenshots and puts them in the /config folder. If you can access that folder then you'll be able to see the screenshot outputs.

I didn't realise and deleted the container after. No switch today. I'm gonna try an older docker image tomorrow and see if it still happens.

**Comment by curator8888** [comment]
I can add a little to this, ive been getting the same issue, so heres what happens for me.

Switching to Go seems to have no problems and it all works correctly:
```
Playwright Hook
APP
 — 01/03/2025 23:06
Octobot
Octobot on. Starting comparison of today's costs...
Octobot
Total potential cost on GO: £20.38 vs your current cost on AGILE: £25.02
Initiating Switch to GO
Octobot
Tariff switch requested successfully.
Octobot
Post-enrolment automatically completed with today's date.
Octobot
Accepted agreement. Switch successful.
Octobot
Verified new agreement successfully. Process finished
```

When switching to Agile I get the following:
```
Octobot
Octobot on. Starting comparison of today's costs...
Octobot
Total potential cost on AGILE: £15.32 vs your current cost on GO: £16.30
Initiating Switch to AGILE
Octobot
Tariff switch requested successfully.
Octobot
Traceback (most recent call last):
  File "/app/main.py", line 347, in run_tariff_compare
    compare_and_switch()
  File "/app/main.py", line 332, in compare_and_switch
    accept_new_agreement()
  File "/app/main.py", line 151, in accept_new_agreement
    result = gql_client.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/gql/client.py", line 469, in execute
    data = loop.run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/gql/client.py", line 367, in execute_async
    return await session.execute(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/gql/client.py", line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'An internal error occurred.', 'locations': [{'line': 2, 'column': 3}], 'path': ['acceptTermsAndConditions'], 'extensions': {'errorType': 'APPLICATION', 'errorCode': 'KT-CT-7899', 'errorDescription': ''}}
```

So on getting this I decided to do it manually and noticed when switching Octopus gives me the Uh Oh page and telling me theres an issue switching right now, but I will receive the email within 1 hour of that message anyway enabling me to swtich.

**Comment by joeShuff** [comment]
Made a test image to log more info and ran it on my AMD arch machine through docker.

User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/131.0.6778.33 Safari/537.36

It did fail and it appears that the login is failing. Credentials are definitely correct.

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/fa7206e7-229f-43b7-af24-36e721468b3a" />

I have tried to set the user agent to the one that works on my Mac and this resulted in the same issue unfortunately. But it works on my mac running the script directly. 

So I don't think it's a user agent issue but thats a good shout, it could be something similar.

**Comment by eelmafia** [comment]
Interesting. Though if Octopus _has_ put a filter on that's even mildly sophisticated just changing the user agent won't do much. Playwright, and especially Chromium, expose A LOT about you. I think Playwright even exposes that you're running an automated browser iirc. 

There's a million ways they'll able to tell it's a bot. https://www.browserscan.net/ shows how many datapoints can be used to detect you. 

We could in theory switch to using https://github.com/daijro/camoufox which is a fork of Playwright enhanced for stealth, but then we'd have to take the project private otherwise there's no point. 

I'm 99% certain this is an anti-bot measure because nothing else makes sense. How else could an old docker image stop working retroactively on Linux but not on Windows/Mac. 

In order to be sure though we should look at the network tab and see what happens with the login request. I wonder if it will point to what's going on. 

>  you can just modify the switching line to not click the button, but locate it.

That's a good idea!

**Comment by joeShuff** [comment]
Maybe you could try the new browser implementation to just prove if it's an antibot measure?

Strange that it works fine when running the bot in pure python though.

**Comment by eelmafia** [comment]
> Maybe you could try the new browser implementation to just prove if it's an antibot measure?
> 
> Strange that it works fine when running the bot in pure python though.

Wait, have you successfully ran the bot in pure python on Linux?

**Comment by eelmafia** [comment]
Update. I was able to log in successfully because I can see the last screenshot taken before it crashed was of my profile's landing page.  Then I got this

```
Traceback (most recent call last):
  File "/app/main.py", line 353, in run_tariff_compare
    compare_and_switch()
  File "/app/main.py", line 311, in compare_and_switch
    switch_tariff(cheapest_tariff.url_tariff_name)
  File "/app/main.py", line 204, in switch_tariff
    page.goto(f"https://octopus.energy/smart/{target_tariff.lower()}/sign-up/?accountNumber={config.ACC_NUMBER}")
  File "/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py", line 9006, in goto
    self._sync(
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://octopus.energy/smart/go/sign-up/?accountNumber=REDACTED", waiting until "load"
```

I'm using `eelmafia/octopus-minmax-bot:test` and the one significant change I made was I switched to using `Firefox` instead of `Chromium`

Now to figure out why `Page.goto: Timeout 30000ms exceeded.` is happening ...

**Comment by eelmafia** [comment]
This should be fixed by https://github.com/eelmafia/octopus-minmax/issues/47 🤞

**Comment by joeShuff** [comment]
> Wait, have you successfully ran the bot in pure python on Linux?

I didn't before, but just setup a venv and got it running just bare metal, and it loaded all the pages fine. This was with your new changes too.

However, I have pushed my modifications to take more screenshots on top of your changes, and I'm still getting the same error as I screenshot above.

But it does look like an incorrect amount of characters are being input for the password. I'll dig more into it tomorrow as it could be a character issue.

**Comment by eelmafia** [comment]
Maybe we were having completely different problems then 🤔😅. Maybe try changing your password temporarily to only English characters and numbers and see if it persists.

**Comment by joeShuff** [comment]
I changed my password to a passphrase with just letters and numbers and it logged in fine and loaded the page fine. Through docker on my AMD arch machine. 

Will swap over to the release build now, but a good one to know for the future that some characters bugger up playwright.

**Comment by robbo21982** [comment]
Still getting error on the newest image:

Octobot on. Starting comparison of today's costs...
Total Consumption today: 20.9880 kWh
Current tariff Octopus Go: £5.87 (£5.37 con + £0.50 s/c)
Potential cost on Flexible Octopus: £5.82 (£5.32 con + £0.50 s/c)
Potential cost on Agile Octopus: £3.83 (£3.33 con + £0.50 s/c)
Potential cost on Cosy Octopus: £5.40 (£4.90 con + £0.50 s/c)

Initiating Switch to Agile Octopus
Octopus Energy website loaded
Traceback (most recent call last):
  File "/app/main.py", line 375, in run_tariff_compare
    compare_and_switch()
  File "/app/main.py", line 333, in compare_and_switch
    switch_tariff(cheapest_tariff.url_tariff_name)
  File "/app/main.py", line 216, in switch_tariff
    page.get_by_placeholder("Email address").click()
  File "/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py", line 15450, in click
    self._sync(
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 300000ms exceeded.
Call log:
  - waiting for get_by_placeholder("Email address")
  -     - locator resolved to <input required="" type="email" name="username" maxlength="512" id="id_username" placeholder="Email address"/>
  -   - attempting click action
  -     2 × waiting for element to be visible, enabled and stable
  -       - element is visible, enabled and stable
  -       - scrolling into view if needed
  -       - done scrolling
  -       - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -     - retrying click action
  -     - waiting 20ms
  -     2 × waiting for element to be visible, enabled and stable
  -       - element is visible, enabled and stable
  -       - scrolling into view if needed
  -       - done scrolling
  -       - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -     - retrying click action
  -       - waiting 100ms
  -     559 × waiting for element to be visible, enabled and stable
  -         - element is visible, enabled and stable
  -         - scrolling into view if needed
  -         - done scrolling
  -         - <div role="dialog" id="countryModal" aria-hidden="false" class="modal modal-open">…</div> intercepts pointer events
  -       - retrying click action
  -         - waiting 500ms

**Comment by joemarshalljm** [comment]
I'm getting this same error

**Comment by eelmafia** [comment]
@joemarshalljm  @robbo21982 Do you have electroverse accounts? 

This should be fixed when https://github.com/eelmafia/octopus-minmax/pull/53 gets merged and we get rid of Playwright.

**Comment by robbo21982** [comment]
> [@joemarshalljm](https://github.com/joemarshalljm) [@robbo21982](https://github.com/robbo21982) Do you have electroverse accounts?
> 
> This should be fixed when [#53](https://github.com/eelmafia/octopus-minmax/pull/53) gets merged and we get rid of Playwright.

Yes I do. And that’s good news!  Thanks for the update.

**Comment by joemarshalljm** [comment]
> [@joemarshalljm](https://github.com/joemarshalljm) [@robbo21982](https://github.com/robbo21982) Do you have electroverse accounts?
> 
> This should be fixed when [#53](https://github.com/eelmafia/octopus-minmax/pull/53) gets merged and we get rid of Playwright.

I don't have electroverse, no. Great news on the update, I'll keep an eye out.

Thank you!

**Comment by eelmafia** [comment]
Playwright is gone so this should be fixed. Don't forget to pull the latest image. You can also get rid of the username/password variables as well. 

Can someone who previously had this issue confirm if it's no longer happening?

**Comment by joemarshalljm** [comment]
I got this error last night:

```
Traceback (most recent call last):
  File "/app/main.py", line 362, in run_tariff_compare
    compare_and_switch()
  File "/app/main.py", line 316, in compare_and_switch
    enrolment_id = switch_tariff(cheapest_tariff.product_code, account_info.mpan)
  File "/app/main.py", line 209, in switch_tariff
    result = gql_client.execute(query)
  File "/usr/local/lib/python3.9/site-packages/gql/client.py", line 469, in execute
    data = loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/gql/client.py", line 367, in execute_async
    return await session.execute(
  File "/usr/local/lib/python3.9/site-packages/gql/client.py", line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'Invalid data.', 'locations': [{'line': 2, 'column': 3}], 'path': ['startOnboardingProcess'], 'extensions': {'errorClass': 'VALIDATION', 'validationErrors': [{'message': 'Existing onboarding process found for MPAN my-number-hiding-this-just-in-case.'}]}}
```

**Comment by curator8888** [comment]
I just want to add that last night I got zero errors, and it was a switch to Agil from Go which is normally where I got my error. So, for me at least it 100% worked. I use docker.

**Comment by eelmafia** [comment]
@joemarshalljm Do you have an export/import MPAN? I wonder if its related to https://github.com/eelmafia/octopus-minmax/issues/60

**Comment by joemarshalljm** [comment]
> [@joemarshalljm](https://github.com/joemarshalljm) Do you have an export/import MPAN? I wonder if its related to [#60](https://github.com/eelmafia/octopus-minmax/issues/60)

No I don't, I don't export anything - no solar or battery

**Comment by joeShuff** [comment]
> 'validationErrors': [{'message': 'Existing onboarding process found for

To me this sounds like octopus is waiting for you to accept terms for a different tariff. I had this, I couldn't join cosy until I agreed ot the agile terms. Even though I immediately swapped to cosy.

**Comment by joemarshalljm** [comment]
> > 'validationErrors': [{'message': 'Existing onboarding process found for
> 
> To me this sounds like octopus is waiting for you to accept terms for a different tariff. I had this, I couldn't join cosy until I agreed ot the agile terms. Even though I immediately swapped to cosy.

This could be it, on a previous night when the script failed it could have got stuck.

I've gone back and accepted the T&Cs from the last time the script failed. Also updated the docker in case it is somehow related to a export MPAN.

Lets see what happens tonight.

**Comment by joemarshalljm** [comment]
SUCCESS

**Comment by eelmafia** [comment]
Closing this as it looks to be resolved
